AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    AllowedPattern: '[A-Za-z0-9-]{1,22}'
    ConstraintDescription: Maximum of 22 alphanumeric characters. Can include hyphens
      (-), but not spaces. Must be unique within your account in an AWS Region.
    Description: SageMaker Notebook instance name
    MaxLength: '22'
    MinLength: '1'
    Type: String
    Default: project

  NotebookInstanceType:
    AllowedValues:
      - ml.t2.medium
      - ml.t3.medium
      - ml.t3.large
      - ml.t3.xlarge
      - ml.t3.2xlarge
      - ml.m5.xlarge
      - ml.m5.2xlarge
      - ml.m5.4xlarge
    ConstraintDescription: Must select a valid notebook instance type.
    Default: ml.t3.medium
    Description: Select Instance type for the SageMaker Notebook
    Type: String

Resources:
  #================================================================================
  # SageMaker Notebook Instance
  #================================================================================
  SAGEMAKER:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        NotebookInstanceName: !Sub ${ProjectName}-notebooks
        NotebookInstanceType: !Ref NotebookInstanceType
        NotebookInstanceRoleArn: !GetAtt IAM.Outputs.SageMakerNotebookInstanceRoleArn
      TemplateURL: https://raw.githubusercontent.com/SofianHamiti/control-tower-for-ml/master/managed-policies/templates/sagemaker_template.yaml
  #================================================================================
  # IAM Role
  #================================================================================
  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/SofianHamiti/control-tower-for-ml/master/managed-policies/templates/iam_template.yaml
  #================================================================================
  # S3 Buckets - data bucket and model bucket
  #================================================================================
  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DataBucketName: !Sub ${ProjectName}-data-${AWS::AccountId}
        ModelBucketName: !Sub ${ProjectName}-models-${AWS::AccountId}
      TemplateURL: https://raw.githubusercontent.com/SofianHamiti/control-tower-for-ml/master/managed-policies/templates/s3_template.yaml
  #================================================================================
  # ECR Repo
  #================================================================================
  ECR:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        RepositoryName: !Sub ${ProjectName}-containers
      TemplateURL: https://raw.githubusercontent.com/SofianHamiti/control-tower-for-ml/master/managed-policies/templates/ecr_template.yaml
