AWSTemplateFormatVersion: 2010-09-09
Description: Create IAM Roles

Resources:
  #================================================================================
  # IAM Role - Notebook Instance
  #================================================================================
  SageMakerNotebookInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

Outputs:
  SageMakerNotebookInstanceRoleArn:
    Value: !GetAtt SageMakerNotebookInstanceRole.Arn