AWSTemplateFormatVersion: 2010-09-09
Description: Create SageMaker Notebook Instance linked with EMR

Parameters:
  NotebookInstanceName:
    Type: String
  NotebookInstanceType:
    Type: String
  NotebookInstanceRoleArn:
    Type: String

Resources:
  SageMakerNotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Ref NotebookInstanceName
      InstanceType: !Ref NotebookInstanceType
      RoleArn: !Ref NotebookInstanceRoleArn
      VolumeSizeInGB: 30

Outputs:
  SageMakerNotebookInstance:
    Value: !Ref SageMakerNotebookInstance
