AWSTemplateFormatVersion: 2010-09-09
Description: Create IAM Roles

Parameters:
  ECRRepository:
    Type: String
  DataBucket:
    Type: String
  ModelBucket:
    Type: String

Resources:
  SageMakerNotebookInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      RoleName: !Sub ${AWS::StackName}-notebook-instance-role
      Policies:
        - PolicyName: SageMakerRestrictedActions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudWatchLogsAccess
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                  - logs:GetLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/sagemaker/*
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-stream:*
              - Sid: CloudWatchMetricsAccess
                Effect: Allow
                Action:
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:ListMetrics
                  - cloudwatch:PutMetricData
                  - cloudwatch:GetMetricData
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DescribeAlarms
                Resource: *
              - Sid: S3Access
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:ListAllMyBuckets
                Resource:
                  - !Sub arn:aws:s3:::${DataBucket}/*
                  - !Sub arn:aws:s3:::${ModelBucket}/*
              - Sid: ECRAccess
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - ecr:SetRepositoryPolicy
                  - ecr:CompleteLayerUpload
                  - ecr:BatchDeleteImage
                  - ecr:UploadLayerPart
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                Resource:
                  - !Ref ECRRepository
              - Sid: PassRole
                Effect: Allow
                  Action:
                    - iam:PassRole
                  Resource: '*'
                  Condition:
                    StringEquals:
                      iam:PassedToService: sagemaker.amazonaws.com
              - Sid: KMSAccess
                Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: '*'
              - Sid: SageMakerAccess
                Effect: Allow
                  Action:
                    - sagemaker:Describe*
                    - sagemaker:List*
                    - sagemaker:CreateTrainingJob
                    - sagemaker:CreateModel
                    - sagemaker:CreateHyperParameterTuningJob
                    - sagemaker:CreateEndpointConfig
                    - sagemaker:CreateEndpoint
                    - sagemaker:UpdateEndpointWeightsAndCapacities
                    - sagemaker:StopHyperParameterTuningJob
                    - sagemaker:UpdateEndpointWeightsAndCapacities
                    - sagemaker:InvokeEndpoint
                    - sagemaker:UpdateEndpoint
                    - sagemaker:DeleteEndpoint
                    - sagemaker:DeleteModel
                    - sagemaker:DeleteEndpointConfig
                Resource: '*'
              - Sid: EC2Access
                Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:CreateNetworkInterfacePermission
                    - ec2:DeleteNetworkInterface
                    - ec2:DeleteNetworkInterfacePermission
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DescribeVpcs
                    - ec2:DescribeDhcpOptions
                    - ec2:DescribeSubnets
                    - ec2:DescribeSecurityGroups
                    - ec2:DescribeVpcEndpoints
                Resource: '*'
Outputs:
  SageMakerNotebookInstanceRoleArn:
    Value: !GetAtt SageMakerNotebookInstanceRole.Arn
