AWSTemplateFormatVersion: 2010-09-09
Description: Create IAM Roles

Parameters:
  NotebookInstanceRoleArn:
    Type: String
  KMSAlias:
    Type: String
    Default: sagemaker-kms-example

Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: allow-root-access-to-key
        Statement:
          - Sid: allow-root-to-delegate-actions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:*
            Resource: '*'
          - Sid: allow-sagemaker-to-use-key
            Effect: Allow
            Principal:
              AWS: !Ref NotebookInstanceRoleArn
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
              - kms:GetKeyPolicy
              - kms:CreateGrant
            Resource: '*'
  KeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${KMSAlias}
      TargetKeyId: !Ref KMSKey
Outputs:
  KMSKeyArn:
    Value: !GetAtt KMSKey.Arn
