AWSTemplateFormatVersion: 2010-09-09
Description: Create SageMaker Notebook Instance linked with EMR

Parameters:
  NotebookInstanceName:
    Type: String
  NotebookInstanceType:
    Type: String
  NotebookInstanceRoleArn:
    Type: String
  SageMakerNotebookSubnet:
    Type: String
  SageMakerNotebookSecurityGroup:
    Type: String
  KMSKeyArn:
    Type: String
  DirectInternetAccess:
    Type: String
    Default: Disabled
  RootAccess:
    Type: String
    Default: Disabled

Resources:
  SageMakerNotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Ref NotebookInstanceName
      InstanceType: !Ref NotebookInstanceType
      RoleArn: !Ref NotebookInstanceRoleArn
      SecurityGroupIds:
        - !Ref SageMakerNotebookSecurityGroup
      SubnetId: !Ref SageMakerNotebookSubnet
      DirectInternetAccess: !Ref DirectInternetAccess
      RootAccess: !Ref RootAccess
      VolumeSizeInGB: 30
      KmsKeyId: !Ref KMSKeyArn

Outputs:
  SageMakerNotebookInstance:
    Value: !Ref SageMakerNotebookInstance
